[project]
name = "mcp-geoportal"
version = "0.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
    "uvicorn>=0.37.0",
]
