# ----------------------------------------
# module name: create_map_link.py
# created on: 2020-03-20
# generated by: Sj
# responsible: Sj
# copyright: Amt für Geoinformation des Kantons Bern
# ----------------------------------------
"""Erstelle einen Link zu einer Karte im Geoportal des Kantons Bern mit vordefinierten Parametern."""


def get_map_link(name_function: str, params: dict ) -> str:
    """Erstelle einen Link zu einer Karte im Geoportal des Kantons Bern mit vordefinierten Parametern.

    Args:
        name_function (str): Name der MCP-Funktion.
        params (dict):  Parameter zur lokalisation des Kartenausschnitts.
                        Erlaubte Parameter: egrid oder (x, y) oder gemeinde -> Lokalisation
                                            scale -> Massstab der Karte
                                            lang -> Sprache der Karte
                                            layers -> Layername

    Returns:
        str: URL-Link zur Kartenansicht im Geoportal des Kantons Bern.
    """
    base_url = "https://www.topo.apps.be.ch/pub/map/?"

    if name_function == "get_naturgefahren_for_egrid":
        egrid = params.get("egrid", "CH294676423526")  # Default EGRID auf Bundeshaus
        scale = params.get("scale", 1000)
        lang = params.get("lang", "de")
        url = f"DIPANU_DIPANUF_KMGDM1=DIPANUF_EGRID={egrid}&addcrosshair=false&scale={scale}&lang={lang}&layers=NATGEFKA_GEFGEB_KMGDM3&legend=True"

    if name_function == "get_gebaeude_in_rote_zonen":
        layers = params.get("layers", "NATGEFKA_SYGEFGEB_KMGDM1")
        lang = params.get("lang", "de")
        url = f"addcrosshair=false&lang={lang}&layers={layers}&legend=True"

    if name_function == "get_bohrprofile_for_egrid":
        egrid = params.get("egrid", "CH294676423526")  # Default EGRID auf Bundeshaus
        scale = params.get("scale", 1000)
        lang = params.get("lang", "de")
        url = f"DIPANU_DIPANUF_KMGDM1=DIPANUF_EGRID={egrid}&addcrosshair=false&scale={scale}&lang={lang}&layers=GEOSOND_GEOSOND_KMGDM1&legend=True"

    full_url = base_url + url
    return full_url
